name: linecoin
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/viniciusm-dev/linecoin

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  bosun: ^0.2.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
